Add step for build go-common image
webdevelop-pro/go-common pull request #25
Opened 2024-06-06 11:46 UTC by Goginet

2024-06-07 18:14 UTC, vladyslav2 commented on .github/workflows/ci.yaml
> +        image: cr.webdevelop.us/webdevelop-pro/postgres:latest
@Goginet we need to have a clear separation been common modules and specific projects. Here we should not use anything from invest project, and why would we need to do it anyway? Why cannot we use just a postgres? Do we need all those tables?

2024-06-07 18:14 UTC, vladyslav2 commented on docker/go.mod
> +go 1.21
Should be go 1.22

2024-06-07 18:15 UTC, vladyslav2 commented on docker/go.mod
> +toolchain go1.22.1
This need to be removed

2024-06-07 18:15 UTC, vladyslav2 commented on docker/readme.md
> +Pre-build docker image for go 1.21.5
go 1.22

2024-06-07 18:16 UTC, vladyslav2 requested changes
Let's separate invest project from go common

2024-06-12 13:59 UTC, Goginet commented on .github/workflows/ci.yaml
> +        image: cr.webdevelop.us/webdevelop-pro/postgres:latest
@vladyslav2 убрал, там был один тест который требовал этого, я его подправил и поменял на обычный образ postgres

2024-06-12 14:00 UTC, Goginet commented on docker/go.mod
> +go 1.21
@vladyslav2 done

2024-06-12 14:22 UTC, vladyslav2 approved these changes

2024-06-18 20:19 UTC, merged